# Generated by Django 3.0.5 on 2020-12-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='21603.png', null=True, upload_to=''),
        ),
    ]
