# Generated by Django 3.0.5 on 2020-12-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0002_auto_20201228_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='21603.png', null=True, upload_to='static/images/'),
        ),
    ]
