# Generated by Django 3.0.5 on 2020-12-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0003_auto_20201228_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='21603.png', null=True, upload_to='images/'),
        ),
    ]
