# Generated by Django 3.0.5 on 2020-12-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0004_auto_20201228_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='user.png', null=True, upload_to='images'),
        ),
    ]
